package com.moses.inspectionapp.ui.navigation

object MainRoute {
    const val Home = "home"
    const val Facilities = "facility"
    const val FacilitySearch = "facility/search"
    const val FacilityEnroll = "facility/enroll"
    const val FacilityDetails = "facility/details"
    const val AssessmentStart = "assessment/start"
    const val AssessmentVisitType = "assessment/visit-type"
    const val AssessmentTeam = "assessment/team"
    const val AssessmentQuestionsPreview = "assessment/questions-preview"
    const val AssessmentChecklist = "assessment/checklist"
    const val AssessmentAnswersReview = "assessment/answers-review"
    const val AssessmentAdjustment = "assessment/adjustment"
    const val AssessmentDecision = "assessment/decision"
    const val AssessmentComments = "assessment/comments"
    const val AssessmentReview = "assessment/review"
    const val Inspections = "inspections"
    const val InspectionDetails = "inspections/details"
    const val InspectionPdf = "inspections/pdf"
    const val Sync = "sync"
    const val SyncConflicts = "sync/conflicts"
    const val Stats = "stats"
    const val Settings = "profile/settings"
    const val Profile = "profile"
    const val CameraCapture = "camera/capture"
    const val EditRecord = "edit/record"
    const val LockedRecord = "locked/record"
    const val StatesDemo = "states"
}
